shfSecurity:
  index:
    security: false
  login:
    security: false
  logout:
    security: true
  noPermission:
    security: false
  exception:
    security: false

homePage:
  index:
    security: false
    #credentials:
     # - [admin, cajero]
  insert:
    security: true
    
    
admin:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
