shfSecurity:
  index:
    security: false
  logoin:
    security: false
  logout:
    security: true

homePage:
  index:
    security: false
    #credentials:
     # - [admin, cajero]
  insert:
    security: true
    
    
admin:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true