all:
  meta:
    - charset="UTF-8"
  javascript:
    - jquery-1.11.1.min.js
    - index.js
    - bootstrap.js
    - bootstrap-popover.js
    - bootstrap-tooltip.js
  stylesheet:
    - bootstrap.css
    - main.css
  favicon: favicon.ico
  title:   


shfSecurity:
  index:
    stylesheet:
      - signin.css

default:
  index:
    javascript:
      - index.js