all:
  meta:
    - charset="UTF-8"
  javascript:
    - jquery-1.11.1.min.js
    - index.js
    - bootstrap.js
    - bootstrap-popover.js
    - bootstrap-tooltip.js
  stylesheet:
    - bootstrap.css
    - main.css
    - signin.css
  favicon: favicon.ico
  title:   


shfSecurity:
  index:
    stylesheet:
      - signin.css

default:
  index:
    javascript:
      - index.js
      
usuario:
  insert:
    stylesheet:
      - form.css
      
evento:
  insert:
    stylesheet:
      - form.css      
      
      
homePage:
  index:
    stylesheet:
      - admin.css
      - bootstrap.css
      #- main.css
      - font-awesome.min.css
      - ionicons.css
    javascript:
      - jquery-1.11.1.js 
      - index.js
      
      
      
      
      
      